GET http://localhost:3001/api/people
###
POST http://localhost:3001/api/people
Content-Type: application/json
{
  "name": "Java",
  "number": "123-456-7890"
}
###
DELETE http://localhost:3001/api/people/1
