### GET Request
GET http://localhost:3001/api/persons

### POST Request
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "123-456-7890"
}

### DELETE Request
DELETE http://localhost:3001/api/persons/1
