GET http://localhost:3001/api/people
###
POST http://localhost:3001/api/people
Content-Type: application/json

{
  "name": "Haskell",
  "number": "123-456-7890"
}
###
DELETE http://localhost:3001/api/people/65db884fa99a92feda0a98a7
